export const services = [
  {
    id_servicio: 1,
    id_usuario: 2,
    nombre_servicio: "Corte de Cabello Masculino",
    descripcion: "Corte moderno con máquina y tijera, incluye lavado.",
    duracion_minutos: 30,
    precio: 12.5,
    imagen_url: "https://example.com/imagenes/corte_hombre.jpg",
    distancia_metros: 500,
  },
  {
    id_servicio: 2,
    id_usuario: 3,
    nombre_servicio: "Manicure y Pedicure",
    descripcion: "Servicio completo de manos y pies con esmalte a elección.",
    duracion_minutos: 30,
    precio: 25.0,
    imagen_url: "https://example.com/imagenes/manicure.jpg",
    distancia_metros: 1200,
  },
  {
    id_servicio: 3,
    id_usuario: 4,
    nombre_servicio: "Clases de Yoga",
    descripcion: "Sesión de yoga grupal para todos los niveles.",
    duracion_minutos: 30,
    precio: 8.0,
    imagen_url: "https://example.com/imagenes/yoga.jpg",
    distancia_metros: 850,
  },
  {
    id_servicio: 4,
    id_usuario: 5,
    nombre_servicio: "Entrenamiento Personal",
    descripcion:
      "Sesiones personalizadas de fitness en gimnasio o a domicilio.",
    duracion_minutos: 30,
    precio: 20.0,
    imagen_url: "https://example.com/imagenes/personal_trainer.jpg",
    distancia_metros: 2000,
  },
  {
    id_servicio: 5,
    id_usuario: 6,
    nombre_servicio: "Clases de Inglés",
    descripcion: "Lecciones personalizadas para principiantes y avanzados.",
    duracion_minutos: 30,
    precio: 15.0,
    imagen_url: "https://example.com/imagenes/ingles.jpg",
    distancia_metros: 3000,
  },
  {
    id_servicio: 6,
    id_usuario: 7,
    nombre_servicio: "Masaje Relajante",
    descripcion: "Masaje de cuerpo completo con aromaterapia.",
    duracion_minutos: 30,
    precio: 30.0,
    imagen_url: "https://example.com/imagenes/masaje.jpg",
    distancia_metros: 950,
  },
  {
    id_servicio: 7,
    id_usuario: 8,
    nombre_servicio: "Clases de Guitarra",
    descripcion: "Aprende guitarra acústica o eléctrica desde cero.",
    duracion_minutos: 30,
    precio: 18.0,
    imagen_url: "https://example.com/imagenes/guitarra.jpg",
    distancia_metros: 1700,
  },
  {
    id_servicio: 8,
    id_usuario: 9,
    nombre_servicio: "Cuidado de Mascotas",
    descripcion: "Paseo de perros y cuidado de gatos a domicilio.",
    duracion_minutos: 30,
    precio: 10.0,
    imagen_url: "https://example.com/imagenes/pets.jpg",
    distancia_metros: 600,
  },
  {
    id_servicio: 9,
    id_usuario: 10,
    nombre_servicio: "Limpieza de Hogar",
    descripcion: "Servicio completo de limpieza en departamentos y casas.",
    duracion_minutos: 30,
    precio: 40.0,
    imagen_url: "https://example.com/imagenes/limpieza.jpg",
    distancia_metros: 2100,
  },
  {
    id_servicio: 10,
    id_usuario: 11,
    nombre_servicio: "Reparación de Computadoras",
    descripcion: "Formateo, limpieza de virus e instalación de software.",
    duracion_minutos: 30,
    precio: 35.0,
    imagen_url: "https://example.com/imagenes/pc_repair.jpg",
    distancia_metros: 1350,
  },
  {
    id_servicio: 11,
    id_usuario: 12,
    nombre_servicio: "Fotografía Profesional",
    descripcion: "Sesiones de fotos para eventos o retratos individuales.",
    duracion_minutos: 30,
    precio: 80.0,
    imagen_url: "https://example.com/imagenes/fotografia.jpg",
    distancia_metros: 3200,
  },
  {
    id_servicio: 12,
    id_usuario: 13,
    nombre_servicio: "Clases de Matemáticas",
    descripcion: "Refuerzo escolar y preparación para exámenes.",
    duracion_minutos: 30,
    precio: 12.0,
    imagen_url: "https://example.com/imagenes/matematicas.jpg",
    distancia_metros: 1500,
  },
  {
    id_servicio: 13,
    id_usuario: 14,
    nombre_servicio: "Clases de Natación",
    descripcion: "Clases en alberca para niños y adultos.",
    duracion_minutos: 30,
    precio: 20.0,
    imagen_url: "https://example.com/imagenes/natacion.jpg",
    distancia_metros: 4000,
  },
  {
    id_servicio: 14,
    id_usuario: 15,
    nombre_servicio: "Reparación de Electrodomésticos",
    descripcion: "Reparación de lavadoras, refrigeradores y hornos.",
    duracion_minutos: 30,
    precio: 50.0,
    imagen_url: "https://example.com/imagenes/electrodomesticos.jpg",
    distancia_metros: 2800,
  },
  {
    id_servicio: 15,
    id_usuario: 16,
    nombre_servicio: "Maquillaje Profesional",
    descripcion: "Maquillaje para bodas, fiestas y sesiones fotográficas.",
    duracion_minutos: 30,
    precio: 45.0,
    imagen_url: "https://example.com/imagenes/maquillaje.jpg",
    distancia_metros: 950,
  },
  {
    id_servicio: 16,
    id_usuario: 17,
    nombre_servicio: "Corte de Cabello Femenino",
    descripcion: "Incluye corte, lavado y peinado.",
    duracion_minutos: 30,
    precio: 20.0,
    imagen_url: "https://example.com/imagenes/corte_mujer.jpg",
    distancia_metros: 1100,
  },
  {
    id_servicio: 17,
    id_usuario: 18,
    nombre_servicio: "Terapia Psicológica",
    descripcion: "Sesiones individuales con psicólogo certificado.",
    duracion_minutos: 30,
    precio: 35.0,
    imagen_url: "https://example.com/imagenes/psicologia.jpg",
    distancia_metros: 2500,
  },
  {
    id_servicio: 18,
    id_usuario: 19,
    nombre_servicio: "Clases de Cocina",
    descripcion: "Aprende recetas internacionales y técnicas de cocina.",
    duracion_minutos: 30,
    precio: 30.0,
    imagen_url: "https://example.com/imagenes/cocina.jpg",
    distancia_metros: 3000,
  },
  {
    id_servicio: 19,
    id_usuario: 20,
    nombre_servicio: "Fotografía de Eventos",
    descripcion: "Cobertura completa de bodas, bautizos y fiestas.",
    duracion_minutos: 30,
    precio: 150.0,
    imagen_url: "https://example.com/imagenes/eventos.jpg",
    distancia_metros: 5000,
  },
  {
    id_servicio: 20,
    id_usuario: 21,
    nombre_servicio: "Clases de Pintura",
    descripcion: "Técnicas de óleo, acuarela y acrílico.",
    duracion_minutos: 30,
    precio: 22.0,
    imagen_url: "https://example.com/imagenes/pintura.jpg",
    distancia_metros: 2000,
  },
];
